version: '3'

services:

  mysql:
    image: mysql/mysql-server:5.7
    container_name: blossom-mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: "blossom"
      MYSQL_PASSWORD: "blossom"
      MYSQL_DATABASE: "blossom"
    ports:
      - "3316:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis:alpine
    container_name: blossom-redis
    command: redis-server --port 6379
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6389:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: blossom-elasticsearch
    environment:
      - node.name=single-node
      - cluster.name=blossom
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300